### ISSUE TITLE
Case counts corrected for testing volume

### ISSUE THREAD

**Issue by michaelmunie** [qjhong/covid19#1]
Sorry, I perhaps incorrectly posted an issue on the github.io project.  Perhaps it belongs here better.

https://github.com/qjhong/qjhong.github.io/issues/1#issue-644864914

**Comment by qjhong** [comment]
It's okay. I just repost my response here. 
=============================================================
Mike: Thanks for your suggestion! I do not agree with them that this correction is valid.

As I understand, this approach of P/T (P:positive, T:total test) is valid only when sampling is random. This is not true in reality, and it could lead to unreasonable conclusions. For example, their correction suggests that current positive number is smaller than that in April in CA. I do not agree. Another counter example is that imagine a state can manipulate and reduce P/T by forcefully increasing T, while the real positive population is independent of T. In other words, imagine we have T and then intentionally expand it by another T. In the second T, people are less likely to show symptoms, tend to be relatively healthy, so P/T becomes smaller.

I believe a reasonable correction is P/(T^a), where 0<a<1. We don't know the real value, but a<1. In my model a=0.25. At least this effect is partially taken into account in my model.
